# Generated by Django 6.1 on 2026-10-06 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='conntent',
            new_name='content',
        ),
    ]
