# Generated by Django 6.1 on 2026-10-06 12:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0003_destination_created_by'),
        ('events', '0005_event_created_by'),
        ('posts', '0002_rename_conntent_post_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='destination',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='destinations.destination'),
        ),
        migrations.AddField(
            model_name='post',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='events.event'),
        ),
    ]
