# Generated by Django 6.1 on 2026-09-01 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interests', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='avartar',
            new_name='avatar',
        ),
        migrations.RemoveField(
            model_name='user',
            name='prev_destinations',
        ),
        migrations.RemoveField(
            model_name='user',
            name='review_rank',
        ),
        migrations.AddField(
            model_name='user',
            name='budget',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='user',
            name='interests',
            field=models.ManyToManyField(blank=True, to='interests.interest'),
        ),
        migrations.AddField(
            model_name='user',
            name='review_points',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=128, verbose_name='password'),
        ),
    ]
