# Generated by Django 6.1 on 2026-10-02 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_rename_avartar_user_avatar_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('adventure_seeker', 'Adventure Seeker'), ('business_creator', 'Business Creator'), ('event_creator', 'Event Creator')], default='adventure_seeker', max_length=30),
        ),
    ]
